packages:
  - apps/*
  - packages/*
  - templates/*
  - '!**/test/**'

minimumReleaseAge: 0

versioning:
  fixed:
    - ['@icebreakers/monorepo', repoctl]
  ignore:
    - '@icebreakers/client'
  changelog:
    storage: repository

allowBuilds:
  '@tailwindcss/oxide': true
  esbuild: true
  msgpackr-extract: true
  sharp: true
  vue-demi: true
  workerd: true
