packages:
  - apps/*
  - packages/*
  - templates/*
  - '!**/test/**'

minimumReleaseAge: 0

allowBuilds:
  '@tailwindcss/oxide': true
  esbuild: true
  msgpackr-extract: true
  sharp: true
  vue-demi: true
  workerd: true
