import { readFile } from 'node:fs/promises'
import path from 'pathe'
import { getWorkspacePackages } from '../../core/workspace'

interface PackageJsonVersion {
  name?: unknown
  version?: unknown
}

interface PackageRelease {
  name: string
  version: string
  content: string
}

function escapeRegExp(value: string) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

function readVersionSection(changelog: string, version: string) {
  const header = new RegExp(`^## ${escapeRegExp(version)}$`, 'm')
  const match = header.exec(changelog)
  if (!match || match.index === undefined) {
    return undefined
  }

  const sectionStart = match.index
  const nextSection = /^## /gm
  nextSection.lastIndex = sectionStart + match[0].length
  const nextMatch = nextSection.exec(changelog)
  const section = changelog.slice(sectionStart, nextMatch?.index ?? changelog.length).trim()
  const content = section.slice(match[0].length).trim()
  return content || undefined
}

async function readPackageRelease(name: string, version: string, rootDir: string) {
  let changelog: string
  try {
    changelog = await readFile(path.join(rootDir, 'CHANGELOG.md'), 'utf8')
  }
  catch {
    return undefined
  }

  const content = readVersionSection(changelog, version)
  if (!content) {
    return undefined
  }
  return { name, version, content }
}

function formatReleases(releases: PackageRelease[]) {
  if (!releases.length) {
    return 'No package changelog entries were generated.'
  }

  const summary = [
    '| Package | Version |',
    '| --- | --- |',
    ...releases.map(release => `| \`${release.name}\` | \`${release.version}\` |`),
  ].join('\n')
  const details = releases
    .map(release => [`## \`${release.name}\` \`${release.version}\``, '', release.content].join('\n'))
    .join('\n\n')

  return [summary, '', '---', '', details].join('\n')
}

/**
 * Builds the release PR body from the changelog sections generated by pnpm.
 * Package manifests are re-read because workspace discovery may be cached
 * before `pnpm version -r` updates their versions.
 */
export async function readWorkspaceVersions(cwd: string) {
  const packages = await getWorkspacePackages(cwd)
  const versions = new Map<string, string>()

  for (const pkg of packages) {
    try {
      const manifest = JSON.parse(await readFile(pkg.pkgJsonPath, 'utf8')) as PackageJsonVersion
      if (typeof manifest.name === 'string' && typeof manifest.version === 'string') {
        versions.set(manifest.name, manifest.version)
      }
    }
    catch {
      // Ignore malformed packages here; pnpm versioning will report them.
    }
  }
  return versions
}

export async function buildReleasePullRequestBody(cwd: string, previousVersions?: Map<string, string>) {
  const packages = await getWorkspacePackages(cwd)
  const releases: PackageRelease[] = []

  for (const pkg of packages) {
    let manifest: PackageJsonVersion
    try {
      manifest = JSON.parse(await readFile(pkg.pkgJsonPath, 'utf8')) as PackageJsonVersion
    }
    catch {
      continue
    }

    if (typeof manifest.name !== 'string' || typeof manifest.version !== 'string') {
      continue
    }
    if (previousVersions?.get(manifest.name) === manifest.version) {
      continue
    }
    const release = await readPackageRelease(manifest.name, manifest.version, pkg.rootDir)
    if (release) {
      releases.push(release)
    }
  }

  return ['# Releases', '', formatReleases(releases)].join('\n')
}
