export const templateChoices = [
  {
    key: 'tsdown',
    label: 'tsdown 打包',
    source: 'tsdown',
    target: 'packages/tsdown',
    category: 'library',
    description: '使用 tsdown 构建的 TypeScript 库包',
  },
  {
    key: 'vue-lib',
    label: 'vue 组件',
    source: 'vue-lib',
    target: 'packages/vue-lib',
    category: 'library',
    description: 'Vue 3 组件库模板，适合沉淀可复用 UI',
  },
  {
    key: 'vue-hono',
    label: 'vue hono 全栈',
    source: 'client',
    target: 'apps/client',
    category: 'app',
    description: 'Vue 3 + Hono 的前后端一体应用模板',
  },
  {
    key: 'hono-server',
    label: 'hono 模板',
    source: 'server',
    target: 'apps/server',
    category: 'service',
    description: 'Hono API 服务模板',
  },
  {
    key: 'vitepress',
    label: 'vitepress 文档',
    source: 'vitepress',
    target: 'apps/website',
    category: 'docs',
    description: 'VitePress 文档站模板',
  },
  {
    key: 'cli',
    label: 'cli 模板',
    source: 'cli',
    target: 'apps/cli',
    category: 'tool',
    description: 'TypeScript 命令行工具模板',
  },
]
