name: Release

on:
  push:
    branches:
      - main
      - alpha
      - beta
      - rc
      - next
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}
env:
  HUSKY: 0

permissions:
  contents: write # to create release (changesets/action)
  issues: write # to post issue comments (changesets/action)
  pull-requests: write # to create pull request (changesets/action)
  id-token: write # to use OpenID Connect token for provenance (changesets/action)

jobs:
  release:
    if: github.ref_name == 'main'
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v7

      - uses: pnpm/action-setup@v6

      - name: Setup Node.js environment
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: pnpm

      - name: Install Dependencies
        run: pnpm i

      - name: Build Release Tooling
        run: pnpm run tooling:build

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm exec repo release stable
        env:
          # this doesn't work but semantic-release works
          # see https://github.com/sonofmagic/npm-lib-rollup-template/blob/main/.github/workflows/release.yml#L46
          # NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          npm_config_registry: https://registry.npmjs.org
          # https://github.com/changesets/changesets/pull/1659
          NPM_CONFIG_PROVENANCE: true

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v7
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  prerelease:
    if: github.ref_name != 'main'
    name: Prerelease
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v7

      - uses: pnpm/action-setup@v6

      - name: Setup Node.js environment
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: pnpm

      - name: Install Dependencies
        run: pnpm i

      - name: Build Release Tooling
        run: pnpm run tooling:build

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Publish Prerelease
        run: pnpm exec repo release pre publish
        env:
          npm_config_registry: https://registry.npmjs.org
          NPM_CONFIG_PROVENANCE: true
